spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

data:
  redis:
    host: localhost
    port: 6379
    password:

jwt:
  secret: TestSecret
  expiration:
    access:
    refresh: 1000 * 60 * 60 * 24 * 7