spring:
  application:
    name: token-service
  jpa:
    show-sql: true
    open-in-view: false

  profiles:
    active: dev

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

jle:
  jwt:
    access-token:
      name: at
      expires: 1m
    refresh-token:
      name: rt
      expires: 7d