### login
POST http://localhost:8082/v1/token/login
Content-Type: application/x-www-form-urlencoded

loginId=test&password=1234

### refresh
POST http://localhost:8082/v1/token/refresh
Content-Type: application/json
Authorization: Bearer
Cookie: AT=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NDE4NDkzODMsImV4cCI6MTc0MTg1Mjk4M30.it1T2V4dAp5cOBCVV1wfJHlhlMa9WWokyOxrF-tU2NCxbxMvanlNalH2YRE21gz9eA76DOGqDjgP-Ol2iYLFK9VMWncDNlpUNhoGKj6WkGSCywu9fdukpWx3n9l1Xv03qRIZnVlnxyvI5kNH57DIk9MLup2yCSA76hSYN9lNBAgGi19iyVwDatax_9VVEy8Ojfwp0k_WLCMyjycbsERaZm0CpNS5MRSeMI4psLeoKhnyIFHJVzL28mFe04fM-Kz0mAOdoqslHsilzzzpyQI1789qDz6fWScygdHCWGEtDSbvsr99k894N2GRgIG-9mV8s52-XDx3lieoyrOExG_kbA
Cookie: RT=eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNzQxODQ5MzgzLCJleHAiOjE3NDI0NTQxODN9.YFrzCcpgW4BgGFUASZhtYhhA2p3seTEbq7NmsmRm7RAyF1mvFBPteVrOXYMjNUl80A-liFo3UhvFhLdzfLSNr7jYKx7F96gOygoJkXAHfYTekmbVWFvjlF1nmyOb-c22Eh5RDuQWEMFCb0StMQYNsnwmG-A9S5SGa74It39iesAA3TYlP3btsbZzarUSEJf79bkWfxnWxvmpdZ-l3v523Oq3FHYBJvQrWITzo2Xjf7cUtfLuQ5Swbm1AUoCPhoNdmp7zeOUm6hQlWk0Tar1rHvvXG9Cezth0He5k4PoBeZlh_Vp4fEqqhRjmpSXLQ82RMaGilNVbrI9RHO8ORy_7tQ

### logout
POST http://localhost:8082/v1/token/logout
Content-Type: application/json
Authorization: Bearer
Cookie: refreshToken=