### login
POST http://localhost:8082/login
Content-Type: application/x-www-form-urlencoded

loginId=test&password=1234

### refresh
POST http://localhost:8082/refresh
Content-Type: application/json
Cookie: at=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NDU3NjA4MDEsImV4cCI6MTc0NTc2NDQwMX0.ZaOOKu_4nGJTjeWCE5RTDagbsQCdewkfq2-5HZ-IsK_IQKbmvMWJEUpjmI6mUUkGOY24fJnyyZCZGLX-SJKSzUVYNpMKzqzg2BVl64gBG1K7NKZV-Su3teHSl1RPM2PpWW19sl-lXtjrZEbM8N_OKRmUMTV55SXfx1Bmsv6wQk1EmVhiDwAAvOjVgrNpiN9nij0l5m-ESuItZF9ALSrhW3-9dOH1H2Fvf0A0OxwllX3NVaPj2A3jx6BXxLqX6TVVBhOpzM_RFNcZ5BBbIyI6CsgRAFFRQZfW4WORajppGZbeWkqIvLs6mKkFDzqLLTAK6uqHQaLIkQYK4YCrF2M3sw
Cookie: rt=eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNzQ1NzYwODAxLCJleHAiOjE3NDYzNjU2MDF9.UqP40_oIijSFd9xtrF4AmeCMhHPEPycv3_uvA9xdvYMz6N6Q71qGmM7zmS3ceuIWdb7wut6V5TFsX51_UaWQGwF9-Kyr13wmWnSuZUew_KAUyAcWE3eVqtsXQcEizn_QMGB_uwa-hrnrA3RxNIShtBQVfFQMNUJrPMrSuzjBE9-Fv97jJuGXESFLP6a0YO8sR_Q2rL9oeXecXHVeAcZBY9PDZyO5_K9mD3oQUYiuN05rbsK22sdsglDgZbUSiEaKL7FxcD9nbMkrX9bjVF04rQmHeXik86ibIPJovnKeGuMWUYG1neTWWoFrDAoX_jo71eyve0hwvwYVflC67Zt0cQ

### logout
POST http://localhost:8082/logout
Content-Type: application/json
Cookie: at=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0Iiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3NDU3NjA4NjksImV4cCI6MTc0NTc2NDQ2OX0.EoEiiZokYgiextMY1Df5B4Ljdc_m8Q28GcEVsEGsvqp0bhnKM-VZmRhfxIg4HLVnB4-UYTjxH_5qKDUiaC2JVWLwDukY5fhXFzkula_QY_5wcVSqfaKfPAHYfQhbfVwEhMEW3PEvXJ1zcs0_jCD3ePS-7aUakdVlKFuRwIyjCOSsINXINk8Y1_V1OZQbvzrizWi4wFemnALcdV-YCncnOEm14t-g6XFpPWaE7MrsNSRarVk-K3TQLw6M8Yt5IqsaWxl9ErfIGIlksAckGyIaTaIzwSUyh8IPpL53HvpT7mjqA0kRf1cs46MdOZhMdltSzhCgdTSFTgN5fQVPRHcZig
Cookie: rt=eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNzQ1NzYwODcwLCJleHAiOjE3NDYzNjU2NzB9.O0NSxLmnZwkPGX-ej8BWhpxUqtQivp40SP-o5jd8XzeKuRyqSJfgHINqSyl6CjrzbvjTcUVIMg7HUBxrEYM3PTIX8QrEjSKjI25bAr6v4WpEpis_zHqykg6LJj3cOPnEsgBRlYiqR2AuOz84rkEzdErKzUKfvsxbdSc5S9FtttSE72Q46FQ-V7ttIUngaG92nPrUu2Pje7X5ew7VXxs1CBcW3Yw2fn0e-FpLhzZ-4fTReZdeF6VdJojvZRxUzuY8ul9kzlLmKKmpuKFpufMaC_xuTDSVUM5UOKZFZSpjZUI8MOZD4GvqQm8HwmUGG26DcsEJmE83nMftFh15zhzSUQ
