### 계정 추가
POST http://localhost:8080/v1/members
Content-Type: application/json

{
  "memberId": "jle",
  "password": "123!@#",
  "name": "testjle",
  "email": "jle@test.com",
  "birthday": "2025-02-06",
  "phoneNumber": "010-2244-5555",
  "gender": "FEMALE",
  "region": "경남",
  "tosAgreement": true,
  "privacyAgreement": true,
  "marketingAgreement": true
}