name: Java CI/CD with Gradle and Docker

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: codethestudent/jle-token-service:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
  
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
  
      - name: Clean and build the application
        run: ./gradlew clean build
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and Push Docker image (multi-platform)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $DOCKER_IMAGE \
            --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export TOKEN_SERVICE_PORT=${{ secrets.TOKEN_SERVICE_PORT }}
            export REDIS_HOST=${{ secrets.REDIS_HOST }}
            export REDIS_PORT=${{ secrets.REDIS_PORT }}
            export REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            export JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }}
            export JWT_PUBLIC_KEY=${{ secrets.JWT_PUBLIC_KEY }}
            export SERVER_HOST=${{ secrets.SERVER_HOST }}
            export API_MEMBER_URL=${{ secrets.API_MEMBER_URL }}
            
            cd docker-compose
            git config credential.helper store
            git pull https://${{ secrets.GIT_ID }}:${{ secrets.GIT_PASSWORD }}@github.com/shoppingmall-platform/docker-compose.git main
            
            docker pull $DOCKER_IMAGE
            docker compose pull token-service
            docker compose up -d token-service
  
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
